spring:
  application:
    name: spring-boot-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
        format_sql: true
        highlight_sql: true

logging:
  level:
    root: info
